config/routes.rb
Todo::Application.routes.draw do
  root :to => "tasks#index"
  resources :user_sessions
  get '/auth/:provider/callback', to: 'sessions#create'
  # resources :friendships do
  #   delete :delete
  # end
  resources :users do
    collection do
      get :logout
      get :forgot_password
      post :forgot_password
      get :change_password
      post :change_password
      get :login
      post :login
      get :settings
    end
  end

  resources :tasks do
    resources :comments
    collection do
      post :share_task
      put :change_progress
      post :change_progress
      delete :delete_share
      put :move_up
      post :move_up
      put :move_down
      post :move_down
      get :task_list
      get :get_task_delete_confirm
      put :change_status
      post :change_status
    end
  end
  resource :user_sessions
  resources :user_verifications, :only => [:show]
  resources :password_resets, :only => [:new, :create, :edit, :update]
  match '/' => 'tasks#index'
  match '/:controller(/:action(/:id))'
  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :user
  has_many :comments
  has_many :task_shares
  has_many :shared_users,:class_name=>'User', :through => :task_shares
  attr_accessible :name,:position,:status
  after_create :initialise_sharetask
  has_one :check_list
  scope :active, -> { where(:status => false) }
  scope :inactive, -> { where(:status=> true) }
  def find_next_task_by_position_and_user_id(position,user_id)
    user=User.find_by_id(user_id)
    user.shared_tasks.active.joins(:task_shares).select("tasks.*,task_shares.position").where("task_shares.position>#{position}").order("task_shares.position DESC").last
  end
  def find_previous_task_by_position_and_user_id(position,user_id)
    user=User.find_by_id(user_id)
    user.shared_tasks.active.joins(:task_shares).select("tasks.*,task_shares.position").where("task_shares.position<#{position}").order("task_shares.position DESC").first
  end
  def self.find_by_position(position)
    Task.joins(:task_shares).select("tasks.*,position").where("task_shares.position=#{position}").first
  end
  def self.search(search,status="all")  
    if search
      if status=="all"
        where('name LIKE ?', "%#{search}%")
      elsif status=="active"
        where('name LIKE ? and status=?', "%#{search}%",false)
      elsif status=="inactive"
        where('name LIKE ? and status=?', "%#{search}%",true)
      end
    else  
      scoped  
    end  
  end  
  private 
    def initialise_sharetask
      ts=TaskShare.new
      ts.task_id=self.id;
      ts.user_id=self.user_id
      unless TaskShare.last.nil?
        ts.position=TaskShare.last.id+1
      else
        ts.position=1
      end
      ts.save!
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_filter :check_loggedin
  def new
  end
  def create
  	@task=Task.new(params[:user])
    @task.user_id=@user.id;
    if @task.save!
      @task=@user.shared_tasks.joins(:task_shares).select("tasks.*,task_shares.position").find(@task.id)
      render :partial => @task
    else
      render :text =>'failed'
    end
  end
  #TODO improve search logic and move to model
  def index
    if @user
      search_text=params[:search]
      @search_text=params[:search]
      if search_text.nil?
        search_text=''
      end
      if params[:completed]=="true"
        @tasks=@user.shared_tasks.search(search_text,"inactive").joins(:task_shares).select("DISTINCT(task_shares.task_id),tasks.*,task_shares.position").order("task_shares.position DESC")
        @tab="completed"
      else
        @tasks=@user.shared_tasks.search(search_text,"active").joins(:task_shares).select("DISTINCT(task_shares.task_id),tasks.*,task_shares.position").order("task_shares.position DESC")
        @tab="home"
      end
       @tasks= @tasks.paginate(:page => params[:page], :per_page => 8,:order=> "id DESC")
    end

  end
  #TODO code repetition , to be removed
  def task_list
    search_text=params[:search]
    if search_text.nil?
      search_text=''
    end
    if @tab=="completed"
        @tasks=@user.shared_tasks.all(:select => "DISTINCT(task_shares.task_id),task_shares.position,tasks.*",:joins => 'INNER  JOIN task_shares ts  ON task_shares.task_id = tasks.id',:order => "task_shares.position DESC",:conditions => "status = 1 and tasks.name LIKE '#{search_text}%'")
    else
        @tasks=@user.shared_tasks.all(:select => "DISTINCT(task_shares.task_id),task_shares.position,tasks.*",:joins => 'INNER  JOIN task_shares ts  ON task_shares.task_id = tasks.id',:order => "task_shares.position DESC",:conditions => "status = 0 and tasks.name LIKE '#{search_text}%'")
    end
    @tasks= @tasks.paginate(:page => params[:page], :per_page => 8,:order=> "position DESC")
    render :partial => "task_list"
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    respond_to do |format| 
      format.html { redirect_to(tasks_url) }
      format.xml { head :ok } 
    end
  end
  #TODO remove ?? . no longer in use
  def change_status
    p params.inspect
    @task = Task.find(params[:task][:id])
    p "Status=#{@task.status}"
    if @task.status==false
      @task.status=true
    else
      @task.status=false
    end
    if @task.save
      #create a new comment
      comment=Comment.new
      comment.task_id=params[:task][:id];
      comment.user_id=current_user.id;
      if @task.status==false
        comment.body="Status Changed to  <span class='green'>UnDone</span>"
      else
        comment.body="Status Changed to  <span class='green'>Done</span>"
      end
      comment.save
      # render :partial => @task
      render :partial =>comment
    else
      render :text => nil
    end
  end
  def move_down
    @position=params[:task][:position]
    @task=Task.find_by_position(@position)
    @down_task=@task.find_previous_task_by_position_and_user_id(@position,@user.id)
    if @task && @down_task
      @task_position=@task.position
      @downtask_position=@down_task.position
      if TaskShare.swap_elements(@task_position,@downtask_position)
        array={:task => @task.id,:other_task=>@down_task.id}
        render :json => array.to_json
      else
         render :text => @task.errors
      end
    else
      render :text => "error"
    end
  end
  def move_up
    @position=params[:task][:position]
    @task=Task.find_by_position(@position)
    @next_task=@task.find_next_task_by_position_and_user_id(@position,@user.id)
    if @task && @next_task
      @task_position=@task.position
      @nexttask_position=@next_task.position
      if TaskShare.swap_elements(@task_position,@nexttask_position)
        array={:task => @task.id,:other_task=>@next_task.id}
        render :json => array.to_json
      else
         render :text => @task.errors
      end
    else
      render :text => "error"
    end
  end
  def show
    task_id=params[:id].to_i
    @users=current_user.friends
    @accessible_tasks=@user.shared_tasks.all(:select => "DISTINCT(task_shares.task_id),task_shares.position,tasks.*",:joins => 'INNER  JOIN task_shares ts  ON task_shares.task_id = tasks.id',:order => "task_shares.position")
    @task=@accessible_tasks.detect{|x| x.id==task_id}
    @shared_users=Task.find_by_id(task_id).shared_users
    @task_owner=@task.user
    if request.xhr? #TODO remove this workaround 
      render :partial => @task
    end
  end
  def get_task_delete_confirm
    @id=params[:id]
    render :partial => "delete_confirm"
  end
  def change_progress
    #TODO to be secured
    task_id=params[:task][:id]
    new_progress=params[:task][:progress]
    @task = @user.shared_tasks.find(task_id)
    previous_progress=@task.progress;
    @task.progress=new_progress
    if previous_progress < @task.progress
      if @task.save 
        #create a new comment
        comment=Comment.new
        comment.task_id=task_id;
        comment.user_id=current_user.id;
        comment.body="Task has been  updated to <span class='green'>#{new_progress}</span> from <span class='green'>#{previous_progress}</span>"
        comment.save
        render comment
      end
    else
      render :text => nil
    end
  end
  def delete_share
    task_id=params[:id]
    task_share=TaskShare.find_by_user_id_and_task_id(current_user.id,task_id)
    if task_share.destroy
      render :text => "success"
    else
      render :text => "failed"
    end
  end
  def share_task
     @task = @user.tasks.find(params[:id])
     @task_id=params[:id];
     #validate TODO
      @user_list=params[:check]
      TaskShare.destroy_all(["task_id = '#{@task_id}' and user_id<>'#{@user.id}'"])
      if @user_list
        for user in @user_list.keys
          unless user == @user.id.to_s
            ts=TaskShare.new
            ts.user_id=user
            ts.task_id=@task_id
            ts.position=TaskShare.last.id+1
            unless ts.save!
              flash[:error]="error"
              redirect to task_path
            end
          end
        end
      end
      redirect_to task_path
  end
  # def share_task
  #    @task = @user.tasks.find(params[:task][:id])
  #    @task_id=params[:task][:id];
  #    #validate TODO
  #     @user_list=params[:task][:user_list]
  #     for user in @user_list
  #        ts=TaskShare.new
  #        ts.user_id=User.find_by_name(user).id
  #        ts.task_id=@task_id
  #        ts.save!
  #     end
  # end
  private
    def check_loggedin
      @user=current_user
      if @user.nil?
        redirect_to login_path
      end
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_delete_confirm.html.erb
<div id="delete_confirm">
	Are you sure you want to delete this entry ?
	<div class="pull-right">
		<button id="delete_task" onclick="delete_task(<%= @id %>)">Yes</button>
		<button id="cancel_delete" onclick="cancel_delete(<%= @id %>)">No</button>
	</div>
</div>

app/views/tasks/_task.erb
<div class="task row" id ="task<%= task.id %>">
	<div class="col-md-8">
		<a href="/tasks/<%= task.id %>"><span class="task-name"><%= task.name %></span> </a>
		<br/>
		<div class="task_entry_bottom">
			by <%=  task.user.name %>
			<br>
			<span class="time"><%=(task.created_at).strftime("%I.%P,  %d %b %Y")%></span>
		</div>
	</div>
	<div class="col-md-4 pull-right button_block">
		<%unless task.status==true %>
			<!-- < % unless task.next_active_task.nil? %> -->
				<button class="up_button" onclick="move_up(<%= task.position %>)"></button>
			<!-- < % end %> -->
			<!-- < % unless task.previous_active_task.nil? %> -->
				<button class="down_button" onclick="move_down(<%= task.position %>)"></button>
			<!-- < % end%> -->
		<% end %>
		<% if task.user_id==@user.id %>
			<button class="delete_button" onclick="confirm_delete_task(<%= task.id %>)"></button>
			<!-- <button class="delete_button" onclick="delete_task(< %= task.id %>)"></button> -->
			<% if task.status==true %>
				<button class="uncheck_button" onclick="change_status(<%= task.id %>)"></button>
			<% else %>
				<button class="check_button" onclick="change_status(<%= task.id %>)"></button>
			<% end %>
		<% else %>
		<% if task.status==true %>
				<button class="uncheck_button" ></button>
			<% else %>
				<button class="check_button"></button>
			<% end %>
		<% end %> 
	</div>
</div>

app/views/tasks/_task_list.html.erb
<%= render :partial => @tasks %>
<% if @tasks.next_page %>
	<button id="load_next" onclick="load_next(<%= @tasks.next_page %>)">load</button>
<% end %>

app/views/tasks/destroy.html.erb
<h1>Tasks#destroy</h1>
<p>Find me in app/views/tasks/destroy.html.erb</p>

app/views/tasks/index.html.erb
<div>
	<div id="wrapper" style="width:100%; text-align:center">
		<div id="top_nav" class="row">
			<div id="tab_nav" class="col-md-7">
				<form>
					<input type="search" id="search_button" name="search" placeholder="Search"> </input>
					<% if @tab=="completed" %>
					<input type="hidden" name="completed" value="true">
					<% end %>
				</form>
			</div>
		  	<nav class="col-md-5" id="index_page_nav">
			  	<div class="dropdown" id="profile_menu">
					<a class="" type="button" id="profile_link" data-toggle="dropdown" aria-expanded="true">
						<%= @user.name %>
						<!-- <span class="caret"></span> -->
					</a>
					<ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1" id="menu_list">
						<li role="presentation" class="disabled"><a role="menuitem" tabindex="-1" href="#" class="inactive "><%= @user.email %></a></li>
						<li role="presentation"><a role="menuitem" tabindex="-1" href="/users" class="active">Users List</a></li>
						<li role="presentation"><a role="menuitem" tabindex="-1" href="/users/change_password" class="active">Change Password</a></li>
					</ul>
				</div>
				<a href="/logout" id="logout">Logout</a>
			</nav>
		</div>
	  	<div id="input">
			<input type="text" name="" id="input_task" class="form-control_back" value="" required="required" pattern="" title="" placeholder="Add your todo Entry hit 'Enter' to post">
			<span id="input_img"></span>
		</div>
		<div id="button_group">
			<% if @tab=="completed" %>
						<a class="nav_button active " href="/tasks">Active</a>
						<a class="nav_button disabled" href="#">Inactive</a>
					<% else %>
						<a class="nav_button  disabled" href="#">Active</a>
						<a class="nav_button active " href="/tasks?completed=true">Inactive</a>
			<% end %>
		</div>
	</div>
	<div id="task_list">
		<%= render :partial => @tasks %>
		<% if @tasks.length <=0 %>
		<center id="result_status">No results</center>
		<% end %>
		<% if @tasks.next_page %>
			<nav id="page-nav" style="width:100%; text-align:center">
			 <% if @search_text.nil? %>
				<a href="/tasks/task_list?page=<%=@tasks.next_page %>"></a>
			<% else %>
				<a href="/tasks/task_list?page=<%=@tasks.next_page %>&search=<%= @search_text%>"></a>
			<% end %>
			</nav>
		<% end %>
		<!-- < %= link_to 'Load More Posts', tasks_path(:page => @tasks.next_page), :class => 'load-more-posts', :remote => true if @tasks.next_page %> -->
	</div>
</div>
<div id="status"></div>

app/views/tasks/new.html.erb
<h1>Tasks#new</h1>
<p>Find me in app/views/tasks/new.html.erb</p>

app/views/tasks/show.html.erb
<!-- <link rel="stylesheet" href="/stylesheets/bootstrap-multiselect.css" type="text/css"/>
 --><div id="top_nav" class="row">
	<div id="tab_nav" class="col-md-8">
		<form action="/tasks">
		<input type="search" id="search_button" name="search" placeholder="Search"> </input>
		<% if @tab=="completed" %>
		<input type="hidden" name="completed" value="true">
		<% end %>
	</form>
	</div>
  	<nav class="col-md-4" id="show_page_nav">
	  	<div class="dropdown" id="profile_menu">
			<a class="" type="button" id="profile_link" data-toggle="dropdown" aria-expanded="true">
				<%= @user.name %>
				<!-- <span class="caret"></span> -->
			</a>
			<ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1" id="menu_list">
				<li role="presentation" class="disabled"><a role="menuitem" tabindex="-1" href="#" class="inactive "><%= @user.email %></a></li>
				<li role="presentation"><a role="menuitem" tabindex="-1" href="/users/change_password" class="active">Change Password</a></li>
			</ul>
		</div>
		<a href="/logout" id="logout">Logout</a>
	</nav>
</div>
<div id="back_menu"><a href="/tasks">< Go Back to home</a></div>
<div id="show_task_box" class="">
		<div id="task-top" class="row">
			<div class="col-md-8">
				<span class="task-name"><%= @task.name %></span>
				<br>
				<span class="time"><%= time_ago_in_words(@task.created_at) %></span>
				<br/>
			</div>
			<div class="col-md-4 pull-right button_block">
				<% if @task.user.id== @user.id %>
					<button class="delete_button" onclick="confirm_delete_task_modal(<%= @task.id %>,true)"></button>
				<% else %>
					<button class="delete_button" onclick="confirm_delete_task_modal(<%= @task.id %>,false)"></button>
				<%  end %>
			</div>
		</div>
		<div id="task-bottom" class="row">
			<div class="col-md-8">
				Task Completion
				<div id="slider_div">
					<div id="slider"></div>
					<span id="slider_count">38%</span>
				</div>
				<% if @shared_users.length >1 %>
				Shared with:
				<% end %>
				<% for user in @shared_users %>
					<% if user.name!=@user.name %>
					 <%=h user.name %>
					<% end %>
				<% end %>
				<!-- Button trigger modal -->
				<% if @task.user.id== @user.id %>
				<br/>
				<button type="button" id="share_button" class="btn btn-default" data-toggle="modal" data-target="#myModal">
				  Share this
				</button>
				<% end %>
			</div>
			<div class="col-md-4 pull-right button_block">
				<% if @task.user.id== @user.id %>
					<% if @task.status==true %>
						<button id="status_button" class="uncheck_button" onclick="change_status(<%= @task.id %>)"></button>
					<% else %>
						<button id="status_button" class="check_button" onclick="change_status(<%= @task.id %>)"></button>
					<% end %>
				<% else %>
					<% if @task.status==true %>
						<button id="status_button" class="uncheck_button" ></button>
					<% else %>
						<button id="status_button" class="check_button"></button>
					<% end %>
				<% end %>
			</div>
		</div>		
</div>
<div id="comment_list">
	<%= render :partial=> @task.comments %>
</div>
<!-- < %= render :partial =>"comments/form" %> -->
<input id="comment_body" name="comment[body]" size="30" type="text" placeholder="Add the comment Hit 'Enter' to post">
<!-- <div class="textarea-wrapper">
    <span class="label label-default">#textarea1</span>
    <textarea class="form-control" id="textarea1" rows="4">:a</textarea>
</div> -->

<span id="task_id" style="display:none;"><%= @task.id %> </span> <br/>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  	<div class="modal-dialog">
	    <div class="modal-content">
	    	<%= form_tag "/tasks/share_task/"+@task.id.to_s,:method=>:put %>
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
					<h6 class="modal-title" id="myModalLabel">Add friends to this task</h6>
				</div>
				<div class="modal-body">
				<!-- <form action="/tasks/share_task/<%= @task.id %>" method="POST"> -->
					<% for user in @users %>
					<% if user.id!=@task.user_id %>
						   	<div id="user<%= user.id%>" class="user_div">
								<input name="check[<%= user.id %>]" type="checkbox" <% if @shared_users.include? user%> checked <%end %> >
								<option class="user_option_list" value="<%=h user.name %>"><%=h user.name %></option>
							</div>
						<% end %>
					<% end %>				
				</div>
				<div class="modal-footer">
					<button type="submit" class="btn" id="save_share_button">Save</button>
					<button type="button" class="btn btn-default" data-dismiss="modal" id="cancel_share_button">Cancel</button>

				</div>
			</form>
		</div>
  	</div>
</div>
<script type="text/javascript">
$(document).ready(function(){
	var task_id= <%= @task.id %>;
	$( "#slider" ).slider( "value", <%= @task.progress %> );
	<% if @task.status==true %>
	$( "#slider" ).slider( "option", "disabled", true );
	<% end %>
});
</script>
<script type="text/javascript">
	//periodic comment updater
	// (function worker() {
	//   $.ajax({
	//     url: '/tasks/<%= @task.id %>/comments', 
	//     success: function(data) {
	//       $('.result').html(data);
	//     },
	//     complete: function() {
	//       // Schedule the next request when the current one's complete
	//       setTimeout(worker, 5000);
	//     }
	//   });
	// })();
</script>

<style type="text/css">
	#status_button {
		margin-top: 16px;
	}
</style>